// import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='container mx-auto min-h-screen'>
        <Navbar></Navbar>
          {children}
          <Footer></Footer>

        </main>
      </body>
    </html>
  );
}
